version: "3.9"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123gabi
      MYSQL_USER: gabriela.schubert
      MYSQL_PASSWORD: 123gabi
      MYSQL_DATABASE: todolist
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "3333:3333"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: gabriela.schubert
      DB_PASSWORD: 123gabi
      DB_NAME: todolist

volumes:
  db_data: