apiVersion: apps/v1               # Versão da API usada para criar o Deployment
kind: Deployment                  # Tipo do recurso Kubernetes: Deployment
metadata:
  name: backend                   # Nome do Deployment
  labels:
    app: backend                  # Rótulo para identificar e selecionar os pods desse Deployment
spec:
  replicas: 1                    # Número de réplicas (pods) desejadas
  selector:
    matchLabels:
      app: backend               # Seleciona os pods que têm esse rótulo (deve combinar com template.metadata.labels)
  template:
    metadata:
      labels:
        app: backend             # Rótulo aplicado nos pods criados por este Deployment
    spec:
      containers:
        - name: backend          # Nome do container dentro do pod
          image: gabrielaschubert/backend:latest  # Imagem Docker que será usada para rodar o container
          ports:
            - containerPort: 3333   # Porta interna do container exposta
          env:
            - name: DATABASE_HOST    # Variável de ambiente DATABASE_HOST usada dentro do container
              value: mysql-service   # Valor definido para a variável DATABASE_HOST
            - name: DATABASE_PORT    # Variável de ambiente DATABASE_PORT usada dentro do container
              value: "3306"          # Valor definido para a variável DATABASE_PORT
