apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: gabrielaschubert/backend
  newName: gabrielaschubert/backend
  newTag: dd61430fc91b9fac5e615a8d7ef74e86935e9a91
apiVersion: kustomize.config.k8s.io/v1beta1
