apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: gabrielaschubert/backend
  newName: gabrielaschubert/backend
  newTag: 2567e2e4d23dd9a92425bcaca228d3ac1e12e9e1
apiVersion: kustomize.config.k8s.io/v1beta1
