apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: gabrielaschubert/backend
  newName: gabrielaschubert/backend
  newTag: 722f2cd1e151c6606d548890511d5d8c4518797e
apiVersion: kustomize.config.k8s.io/v1beta1
