apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: gabrielaschubert/backend
  newName: gabrielaschubert/backend
  newTag: e351655116732e67cf7fb18772c76d03ce0ca568
apiVersion: kustomize.config.k8s.io/v1beta1
