apiVersion: v1                   # Versão da API
kind: Service                    # Tipo de recurso: Service
metadata:
  name: backend                  # Nome do Service (usado para acessar o backend internamente no cluster)

spec:
  selector:
    app: backend                 # Seleciona os pods com esse rótulo (deve bater com os labels do Deployment)
  ports:
    - protocol: TCP              # Protocolo de rede
      port: 80                   # Porta exposta pelo Service (usada internamente no cluster)
      targetPort: 3333           # Porta que o container realmente escuta (a do Node.js backend)
  type: ClusterIP                # Tipo de Service (ClusterIP = acessível apenas dentro do cluster)
